name: Check Links

on:
  push:
    branches:
      - link_checker  # TODO: change to main to after testing
  workflow_dispatch:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          fail: false
          # args to check source files without building
          # './**/*.md' './**/*.html' './**/*.rst'
          args: >
            ./_site/**/*.html
            --max-concurrency 1 --no-progress 
            --accept '100..=103,200..=399, 429'
            --exclude https://doi.org/
        env:
          # avoid 429 errors (too many requests) on github.com api requests
          GITHUB_TOKEN: ${{secrets.TOKEN_GITHUB}}
